<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWr4IxxH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWr4IxxH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWr4IxxH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWr4IxxH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWr4IxxH\App_KernelDevDebugContainer([
    'container.build_hash' => 'Wr4IxxH',
    'container.build_id' => '9c859149',
    'container.build_time' => 1621086483,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWr4IxxH');
