<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9GoOcQH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9GoOcQH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9GoOcQH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9GoOcQH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container9GoOcQH\App_KernelDevDebugContainer([
    'container.build_hash' => '9GoOcQH',
    'container.build_id' => '101f5560',
    'container.build_time' => 1620903261,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9GoOcQH');
